site_name: "Unipressed"
theme:
  name: "material"
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: true
          heading_level: 4
          show_root_toc_entry: true
- include-markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js