[tool.poetry]
name = "unipressed"
version = "0.2.0"
description = "Comprehensive Python client for the Uniprot REST API"
authors = ["Michael Milton <michael.r.milton@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://multimeric.github.io/Unipressed"
repository = "https://github.com/multimeric/Unipressed"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.28.1"
typing-extensions = "^4.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
mkdocstrings = {extras = ["python"], version = "^0.19.0"}
mkdocs = "^1.3.1"
mkdocs-material = "^8.3.9"
mkdocs-include-markdown-plugin = "^3.6.1"
pre-commit = "^2.20.0"
types-requests = "^2.28.7"
typer = "^0.6.1"
inflection = "^0.5.1"
black = "^22.6.0"
scikit-bio = { version = "^0.5.7", python = ">=3.8, <4.0"}
jupyter = { version = "^1.0.0", python = ">=3.8" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.mypy]
disable_error_code = "misc"
show_error_codes = true
files = "unipressed/"

[tool.pyright]
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportMissingTypeArgument = false
reportPrivateUsage = false